#!/usr/bin/env perl
#
# Perl script to add Arch Logo to i3Blocks
# Requires package ttf-font-logos
# Available in the AUR
#

use strict;
use warnings;
use utf8;

my $archlogo;
my $full_text;

$archlogo = "<span font_family='font-logos'color='#1793D0'>\N{U+F103}</span>";
$full_text = "$archlogo  ";

print "$full_text\n";

exit(0);

