#!/bin/bash
#
# Basic bash script:
# To extract brightness levels from xbacklight
#
# Requires package ttf-font-awesome
# Availabe in the AUR

ICON=$(echo -e '\uF042')
XLEVEL=$(xbacklight)
BRIGHTNESS=$(printf "%.0f\n" "$XLEVEL")

echo "<span color='$icocol'> $ICON</span> $BRIGHTNESS%  "

exit 0

