#!/usr/bin/env perl
#
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
#
# Licensed under the terms of the GNU GPL v3, or any later version.
#
# This script parses "acpi" command to read battery status.
#
# Requires package acpi
# Adapted by Wayne Murphy-Jerrett 

use strict;
use warnings;
use utf8;

my $acpi;
my $status;
my $percent;
my $ac_adapt;
my $full_text;
my $batt_icon;
my $bat_number = $ENV{BAT_NUMBER} || 0;
my $chr_icon;
my $dis_icon;
my $full_icon;
my $pwr_icon;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b 2>/dev/null| grep 'Battery $bat_number' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if (not defined($acpi)) {
    # don't print anything to stderr if there is no battery
    exit(0);
}
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) {
	die "$acpi\n";
}

# Set percentage and relevant battery icon
$percent = $2;
if ($percent < 10) {
	$batt_icon = "\N{U+F244}";
} elsif ($percent < 30) {
	$batt_icon = "\N{U+F243}";
} elsif ($percent < 60) {
	$batt_icon = "\N{U+F242}";
} elsif ($percent < 80) {
	$batt_icon = "\N{U+F241}";
} elsif ($percent <= 100) {
	$batt_icon = "\N{U+F240}";
}

# Get status and use it to set charge state icon
$chr_icon = " \N{U+F0e7}";
$dis_icon = "";
$full_icon = "";
$status = $1;

if ($status eq 'Discharging') {
	$pwr_icon = "$dis_icon";
} elsif ($status eq 'Charging') {
	$pwr_icon = "$chr_icon";
} elsif ($status eq 'Full') {
	$pwr_icon = "$full_icon";
} elsif ($status eq 'Unknown') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);
	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;
		if ($ac_adapt eq 'on-line') {
			$pwr_icon .= "$chr_icon";
		} elsif ($ac_adapt eq 'off-line') {
			$pwr_icon .= "$dis_icon";
		}
	}
}

# Concatenate text and output
$full_text .= "  <span weight='900' color='#cf0a0a'>$batt_icon</span>";
$full_text .= "$pwr_icon";
$full_text .= " $percent%  ";
print "$full_text\n";

# consider urgent flag only on discharge
if ($status eq 'Discharging') {
	if ($percent < 10) {
		exit(33);
	}
}

exit(0);

