#!/bin/bash
#
# Basic bash script:
# To extract brightness levels from xbacklight
#
# Requires package ttf-font-awesome
# Availabe in the AUR


ICON=$(echo -e '\uF042')
XLEVEL=$(xbacklight)
BRIGHTNESS=$(printf "%.0f\n" "$XLEVEL")

echo " $ICON $BRIGHTNESS%  "

exit 0

