#!/bin/bash
#
# Basic bash script:
# To extract volume levels from amixer
#
# Requires package ttf-font-awesome
# Availabe in the AUR

ICON=$(echo -e '\uF028')
SOUNDON=$(amixer -M get IEC958,0 | grep Mono: |  awk '{print $3}'| sed 's/[^a-z\%]//g')
VOLUME=$(amixer -M get spdif1Master | grep Right | grep % | awk '{print $4}'| sed 's/[^0-9\%]//g')
TEXT=$VOLUME

if [ $SOUNDON = 'off' ]
then
	ICON=$(echo -e '\uF6A9')
	TEXT='--'
fi

FULLTEXT=" <span color='$icocol'>$ICON</span> $TEXT  "
SHORTEXT=""

echo "$FULLTEXT"
echo "$SHORTEXT"

exit 0

