#!/bin/bash
#
# Basic bash script:
# Can be used later to add functionality to time block
#
# Requires package ttf-font-awesome
# Availabe in the AUR


ICON=$(echo -e '\uF017')
DAY_TIME=$(date +"%a %H:%M")

echo "<span font_family='FontAwesome' weight='900' color='$icocol'> $ICON</span> $DAY_TIME  "

exit 0

