#!/bin/bash
#
# Basic bash script:
# Used to check for system updates in pacman
# Can be used later to add functionality to user block.
# 
# Required pacman-contrib
#
# Requires package ttf-font-awesome
# Available in the AUR


ICON=$(echo -e '\uF0AD')
NUM_UPDATES=$(checkupdates | wc -l)

echo "<span font_family='FontAwesome' weight='900'> $ICON</span> $NUM_UPDATES Updates  "

exit 0

