#!/bin/bash
#
# Basic bash script:
# To extract volume levels from amixer
#
# Requires package ttf-font-awesome
# Availabe in the AUR

ICON=$(echo -e '\uF028')
VOLUME=$(amixer -M get PCM | grep Right| grep % | awk '{print $5}'|sed 's/[^0-9\%]//g')

FULLTEXT=" <span color='$icocol'>$ICON</span> $VOLUME  "
SHORTEXT=""

echo "$FULLTEXT"
echo "$SHORTEXT"

exit 0

