#!/bin/bash
#
# Basic bash script:
# To extract vlume levels from amixer
#
# Requires package ttf-font-awesome
# Availabe in the AUR



ICON=$(echo -e '\uF028')
VOLUME=$(amixer -M get Master |grep % |awk '{print $4}'|sed 's/[^0-9\%]//g')

echo " $ICON $VOLUME  "

exit 0

